"""Generate a large set of near-level opening positions with OUR OWN engine.

Why: tests/openings.py has 12 positions. A 500-game match replays each ~40
times, so games are heavily correlated and every SPRT error bar this project
has reported was optimistically narrow. A foreign 300-position set was tried
first (tools/openings300_ourfilter.fen); scored by our eval it ranged -1088 to
+1240 cp because it was filtered by a much weaker evaluator. This builds the
set from scratch so it is balanced by construction, by the engine that will
actually play it, and carries no provenance question.

Method: from the start position play 8-12 plies, each chosen at random among
the top-K moves by our static eval (king walks excluded), then keep the
position only if a short real search scores it within +-MAX_ABS cp. Dedupe.

Usage (idle machine only -- this is CPU-heavy):
    .venv\Scripts\python.exe tools\gen_openings.py --n 400 --out tests\openings_gen.fen
"""
import argparse, os, random, sys, time
import numpy as np
import chess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", default=os.path.join(ROOT, "checkpoints", "syzygy"))
    ap.add_argument("--n", type=int, default=400)
    ap.add_argument("--out", default=os.path.join(ROOT, "tests", "openings_gen.fen"))
    ap.add_argument("--max-abs", type=int, default=50)
    ap.add_argument("--min-ply", type=int, default=8)
    ap.add_argument("--max-ply", type=int, default=12)
    ap.add_argument("--topk", type=int, default=4)
    ap.add_argument("--search-ms", type=int, default=150)
    ap.add_argument("--seed", type=int, default=20260909)
    args = ap.parse_args()

    sys.path.insert(0, args.engine)
    import agent
    from ca_search import search_root
    from ca_eval import evaluate
    from ca_position import MAX_PLY
    rng = random.Random(args.seed)

    def static_white(board):
        agent._sync_position(board)
        s = int(evaluate(agent._BB, agent._OCC, agent._MAIL, agent._ST))
        return s if board.turn == chess.WHITE else -s

    def search_white(board, ms):
        agent._sync_position(board)
        agent._REP[0] = np.uint64(agent._HSH[0])
        agent._INFO[0] = 1
        now = time.time()
        agent._CTRL[0] = now + ms / 1000.0
        agent._CTRL[1] = now + ms / 1000.0
        search_root(agent._BB, agent._OCC, agent._MAIL, agent._ST, agent._HSH,
                    agent._UNDO, agent._UNDO_H, agent._MOVES, agent._MSCORES,
                    agent._TT_KEY, agent._TT_DATA, agent._KILLERS, agent._HISTORY,
                    agent._COUNTER, agent._REP, MAX_PLY - 8, agent._INFO, agent._CTRL)
        s = int(agent._INFO[5])
        return s if board.turn == chess.WHITE else -s

    def reasonable(board, mv):
        if board.piece_type_at(mv.from_square) == chess.KING and not board.is_check() \
                and not board.is_castling(mv):
            return False
        return True

    kept, seen, tried = [], set(), 0
    t0 = time.time()
    while len(kept) < args.n:
        tried += 1
        b = chess.Board()
        target = rng.randint(args.min_ply, args.max_ply)
        ok = True
        for _ in range(target):
            cands = []
            for mv in b.legal_moves:
                if not reasonable(b, mv):
                    continue
                b.push(mv)
                if b.is_game_over():
                    b.pop(); continue
                s = static_white(b)
                b.pop()
                # rank from the mover's point of view
                cands.append((s if b.turn == chess.WHITE else -s, mv))
            if len(cands) < args.topk:
                ok = False; break
            cands.sort(key=lambda t: -t[0])
            b.push(rng.choice(cands[:args.topk])[1])
        if not ok or b.is_check() or b.legal_moves.count() < 20:
            continue
        key = " ".join(b.fen().split()[:4])
        if key in seen:
            continue
        s = search_white(b, args.search_ms)
        if abs(s) > args.max_abs:
            continue
        seen.add(key)
        kept.append((s, b.fen()))
        if len(kept) % 25 == 0:
            print("  %4d kept / %5d tried   %.0fs" % (len(kept), tried, time.time() - t0),
                  flush=True)

    with open(args.out, "w") as fh:
        fh.write("# %d near-level openings generated by tools/gen_openings.py\n"
                 "# engine=%s  search=%dms  |score|<=%dcp  seed=%d\n"
                 % (len(kept), os.path.basename(args.engine), args.search_ms,
                    args.max_abs, args.seed))
        for s, f in kept:
            fh.write("%s\n" % f)
    scores = [s for s, _ in kept]
    print("wrote %s: %d positions, score mean %+.1f sd %.1f, %.0fs"
          % (args.out, len(kept), sum(scores) / len(scores),
             (sum((x - sum(scores) / len(scores)) ** 2 for x in scores) / len(scores)) ** 0.5,
             time.time() - t0))


if __name__ == "__main__":
    main()
